neck = int(input('Neck Length:\n'))
body = int(input('Body Height:\n'))
leg = int(input('Leg Height:\n'))

print('')

print('    _..-Y  |  |  Y-._')
print('.--"   ||  |  |  |   "-.')
print(' |______________________|\n' * body, end='')
print(' |______________________|', ' ' * neck + '   _____')
print(' L______________________[' + '-' * neck + '----------).')
print('I____________________ [__L][----(_}--P')
print('L________________________j~ \'+++++++//')
print('\\________________________]')
print('  [___________________]')
print('     I--I"~~"""~~"I--I')
print('     |\\n|         |\\n|\n' * leg, end="")
print('     ([])         ([])')
print('    /||||\\       /||||\\')
print('   |=}--{=|     |=}--{=|')
print('  .-4----4-.   .-4----4-.')
